[package]
authors    = ["Darwinia Network <hello@darwinia.network>"]
edition    = '2018'
homepage   = "https://darwinia.network/"
license    = "GPL-3.0"
name       = 'parachain-runtime'
repository = "https://github.com/darwinia-network/parachain/"
version    = '0.1.0'

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }
serde = { version = "1.0.115", default-features = false, optional = true, features = ["derive"] }

cumulus-token-dealer = { path = "../pallets/token-dealer", default-features = false }
parachain-info       = { path = "../pallets/parachain-info", default-features = false }

# Substrate dependencies
frame-executive                   = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
frame-support                     = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
frame-system                      = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
pallet-randomness-collective-flip = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
pallet-sudo                       = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
pallet-timestamp                  = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
pallet-transaction-payment        = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
sp-api                            = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
sp-block-builder                  = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
sp-core                           = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
sp-inherents                      = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
sp-io                             = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
sp-offchain                       = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
sp-runtime                        = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
sp-session                        = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
sp-std                            = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
sp-transaction-pool               = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
sp-version                        = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }

# Cumulus dependencies
cumulus-message-broker    = { git = "https://github.com/paritytech/cumulus", default-features = false, rev = '35f60b1e90145714730d372b5067d9c392884ac9' }
cumulus-parachain-upgrade = { git = "https://github.com/paritytech/cumulus", default-features = false, rev = '35f60b1e90145714730d372b5067d9c392884ac9' }
cumulus-primitives        = { git = "https://github.com/paritytech/cumulus", default-features = false, rev = '35f60b1e90145714730d372b5067d9c392884ac9' }
cumulus-runtime           = { git = "https://github.com/paritytech/cumulus", default-features = false, rev = '35f60b1e90145714730d372b5067d9c392884ac9' }
cumulus-upward-message    = { git = "https://github.com/paritytech/cumulus", default-features = false, rev = '35f60b1e90145714730d372b5067d9c392884ac9' }

# Darwinia dependencies
darwinia-balances   = { default-features = false, git = "https://github.com/darwinia-network/darwinia-common", branch = "rococo-branch" }
darwinia-header-mmr = { default-features = false, git = "https://github.com/darwinia-network/darwinia-common", branch = "rococo-branch" }
darwinia-support    = { default-features = false, git = "https://github.com/darwinia-network/darwinia-common", branch = "rococo-branch" }

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.6" }

[features]
default = ["std"]
std     = [
	"codec/std",
	"serde",
	"sp-api/std",
	"sp-std/std",
	"sp-io/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-version/std",
	"sp-offchain/std",
	"sp-session/std",
	"sp-block-builder/std",
	"sp-transaction-pool/std",
	"sp-inherents/std",
	"frame-support/std",
	"frame-executive/std",
	"frame-system/std",
	"pallet-randomness-collective-flip/std",
	"pallet-timestamp/std",
	"pallet-sudo/std",
	"pallet-transaction-payment/std",
	"parachain-info/std",
	"cumulus-runtime/std",
	"cumulus-parachain-upgrade/std",
	"cumulus-message-broker/std",
	"cumulus-upward-message/std",
	"cumulus-primitives/std",
	"cumulus-token-dealer/std",
	"darwinia-balances/std",
	"darwinia-header-mmr/std",
	"darwinia-support/std",
]
# Will be enabled by the `wasm-builder` when building the runtime for WASM.
runtime-wasm = [
	"cumulus-upward-message/runtime-wasm",
]
